name: WPCraft
version: "0.1"
main: cloud.wpcom.WPCraft
author: "WPCom"
api-version: 1.18
commands:
  bc:
    description: Send a broadcast to all players in the server, using proper prefixes
    usage: /<command> <message>